# Generated by Django 4.2.1 on 2023-06-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_orderitem_variant_id'),
        ('customer', '0007_alter_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='product',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='orders',
            field=models.ManyToManyField(blank=True, to='order.order'),
        ),
    ]
