# Generated by Django 4.2.1 on 2023-06-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_orderitem_variant_id'),
        ('customer', '0008_remove_orderhistory_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
    ]
