# Generated by Django 4.2.1 on 2023-06-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_orderhistory_extra_variable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
