# Generated by Django 4.2.1 on 2023-07-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_customer_address_customer_address_line_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Whishlist',
        ),
    ]
