# Generated by Django 4.2.1 on 2023-06-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_discount_alter_coupon_min_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(help_text='Coupon valid to'),
        ),
    ]
