# Generated by Django 4.2.1 on 2023-06-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_remove_coupon_valid_from_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(help_text='Discount in Percentage (%)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, help_text='Minimum amount to apply coupon ($)', max_digits=10),
        ),
    ]
