# Generated by Django 4.2.1 on 2023-07-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_discount_alter_coupon_min_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='value',
        ),
    ]
