# Generated by Django 4.2.1 on 2023-07-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_rename_discount_coupon_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(default='Coupon valid for minimum purchases of $', help_text='Coupon description', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Discount in Percentage (%)', max_digits=5),
        ),
    ]
