# Generated by Django 4.2.1 on 2023-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='ProductSubCategory',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
