# Generated by Django 4.2.1 on 2023-05-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productsize_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
