# Generated by Django 4.2.1 on 2023-05-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
