# Generated by Django 4.2.1 on 2023-05-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_trending_metaattributes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaAttributes',
            new_name='MetaAttribute',
        ),
    ]
