# Generated by Django 4.2.1 on 2023-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_metaattributes_metaattribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metaattribute',
            old_name='meta_key',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='metaattribute',
            name='meta_value',
        ),
        migrations.AddField(
            model_name='metaattribute',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaattribute',
            name='keywords',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
