# Generated by Django 4.2.1 on 2023-05-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_meta_key_metaattribute_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metaattribute',
            old_name='title',
            new_name='meta_key',
        ),
        migrations.RemoveField(
            model_name='metaattribute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metaattribute',
            name='keywords',
        ),
        migrations.AddField(
            model_name='metaattribute',
            name='meta_value',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
