# Generated by Django 4.2.1 on 2023-05-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_category_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
