# Generated by Django 4.2.1 on 2023-05-29 20:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_tag_product_product_enabled_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Is this product Enabled?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='Is this product in Trending?'),
        ),
    ]
