# Generated by Django 4.2.1 on 2023-05-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_description_alter_product_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-30 01:07'),
            preserve_default=False,
        ),
    ]
