# Generated by Django 4.2.1 on 2023-05-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_productvariant_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
