# Generated by Django 4.2.1 on 2023-06-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_product_image_remove_productvariant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='images',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
