# Generated by Django 4.2.1 on 2023-06-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_productvariant_images_delete_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='images',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='images',
            field=models.ManyToManyField(to='product.productimage'),
        ),
    ]
