# Generated by Django 4.2.1 on 2023-06-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_productvariant_images_productvariant_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='images',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
