# Generated by Django 4.2.1 on 2023-06-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_product_image_product_price_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
