# Generated by Django 4.2.1 on 2023-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_remove_productvariant_stock_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(default=1, upload_to='images/products'),
            preserve_default=False,
        ),
    ]
