# Generated by Django 4.2.1 on 2023-06-20 08:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
        ('product', '0043_alter_product_description_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='\n<h2><img alt="" src="https://i.imgur.com/e6bpDkz.png" style="height:33px; width:42px" /> <img alt="" src="https://imgur.com/a/LpSz4ZC" />&nbsp; Nainah Collection</h2>\n\n<hr />\n<p>A fashion&nbsp;shoe with gladiator straps that you can wear in different styles.</p>\n\n<p><img alt="" src="http://localhost:8000/media/images/products/69410c95-c8a5-466f-b646-d43e20988fc0_3sFJW96.jpg" style="height:80px; width:100px" /><img alt="" src="http://localhost:8000/media/images/products/1ab080d3-71ca-450b-a865-ad788bba60e9.jpg" style="height:113px; width:90px" /><img src="http://localhost:8000/media/images/products/0a9a3d38-0f17-4e2c-8211-20325ea22102-1320x1524.jpg" style="height:125px; width:108px" /></p>\n\n<p>Fashion, Elegance, and Comfort for all Seasons.</p>\n'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10, validators=[product.utils.validator_price]),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.tag'),
        ),
    ]
