# Generated by Django 4.2.1 on 2023-06-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_product_offert_price_alter_productvariant_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offert_price',
            new_name='old_price',
        ),
    ]
