# Generated by Django 4.2.1 on 2023-06-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_rename_offert_price_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
