# Generated by Django 4.2.1 on 2023-06-22 07:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_remove_product_color_remove_product_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='\n<h2><img alt="" src="https://i.imgur.com/e6bpDkz.png" style="height:33px; width:42px" /> <img alt="" src="https://imgur.com/a/LpSz4ZC" />&nbsp; Nainah Collection</h2>\n\n<hr />\n<p>A fashion&nbsp;shoe with gladiator straps that you can wear in different styles.</p>\n\n<p>It is made of high quality materials, durable enough for your daily wearing.</p>\n\n<p>Stylish and fashion design make you more attractive.</p>\n\n<p>Fashion, Elegance, and Comfort for all Seasons.</p>\n'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=100, null=True),
        ),
    ]
