# Generated by Django 4.2.1 on 2023-06-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_remove_productattribute_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductVariantAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
