# Generated by Django 4.2.1 on 2023-06-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_varianttype_variante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variante',
        ),
        migrations.DeleteModel(
            name='VariantType',
        ),
    ]
