# Generated by Django 4.2.1 on 2023-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_alter_productvariant_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=1, help_text='Stock of this variant'),
        ),
    ]
