# Generated by Django 4.2.1 on 2023-07-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_productvariant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaattribute',
            name='meta_key',
        ),
        migrations.RemoveField(
            model_name='metaattribute',
            name='meta_value',
        ),
        migrations.AddField(
            model_name='metaattribute',
            name='meta_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metaattribute',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='metaattribute',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metaattribute',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
