# Generated by Django 4.2.1 on 2023-07-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_remove_metaattribute_meta_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaattribute',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
