# Generated by Django 4.2.1 on 2023-07-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_metaattribute_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('#000000', 'Black'), ('#FFFFFF', 'White'), ('#FF0000', 'Red'), ('#0000FF', 'Blue'), ('#00FF00', 'Green'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#808080', 'Grey'), ('#C0C0C0', 'Silver'), ('#FFD700', 'Gold'), ('#F5F5DC', 'Beige'), ('#CD7F32', 'Bronze'), ('#B87333', 'Copper'), ('#FFFFFF', 'Clear'), ('#FFFDD0', 'Cream'), ('#FFFFFF', 'Multi'), ('#000080', 'Navy'), ('#D2B48C', 'Tan'), ('#40E0D0', 'Turquoise'), ('#FFFFFF', 'Other')], max_length=100, null=True),
        ),
    ]
