# Generated by Django 4.2.1 on 2023-07-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_alter_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Is this product Enabled?'),
        ),
    ]
