# Generated by Django 4.2.1 on 2023-07-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0031_size_color'),
        ('product', '0061_alter_product_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Nainah Collection', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setting.color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setting.size'),
        ),
    ]
