# Generated by Django 4.2.1 on 2023-05-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-create_at'], 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='created',
            new_name='create_at',
        ),
    ]
