# Generated by Django 4.2.1 on 2023-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={},
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='contenido',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
