# Generated by Django 4.2.1 on 2023-07-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='contenido',
            new_name='content',
        ),
    ]
