# Generated by Django 4.2.1 on 2023-07-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_authorizenettransaction_delete_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorizeNetTransaction',
            new_name='Transaction',
        ),
    ]
