# Generated by Django 4.2.1 on 2023-05-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventatest', '0002_rename_cliente_venta_clientes_venta_cliente_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
