# Generated by Django 4.2.1 on 2023-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_show_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this catalog active?'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='show_quantity',
            field=models.PositiveIntegerField(choices=[(4, 4), (8, 8)], default=8, help_text='Show quantity of products in catalog?'),
        ),
    ]
