# Generated by Django 4.2.1 on 2023-06-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalog_active_alter_catalog_show_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='New Collection', help_text='Name of the catalog', max_length=100),
        ),
    ]
