# Generated by Django 4.2.1 on 2023-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catalog_options_catalog_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcatalog',
            options={'ordering': ['-order'], 'verbose_name': 'Product Catalog', 'verbose_name_plural': 'Product Catalogs'},
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
