# Generated by Django 4.2.1 on 2023-06-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productcatalog_options_productcatalog_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcatalog',
            options={'ordering': ['-catalog'], 'verbose_name': 'Product Catalog', 'verbose_name_plural': 'Product Catalogs'},
        ),
        migrations.RemoveField(
            model_name='productcatalog',
            name='order',
        ),
    ]
