# Generated by Django 4.2.1 on 2023-07-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_alter_product_enabled'),
        ('catalog', '0007_alter_productcatalog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='catalogs', to='product.product'),
        ),
        migrations.DeleteModel(
            name='ProductCatalog',
        ),
    ]
