# Generated by Django 4.2.1 on 2023-07-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_alter_product_enabled'),
        ('catalog', '0008_catalog_products_delete_productcatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.productvariant'),
        ),
    ]
