# Generated by Django 4.2.1 on 2023-07-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_alter_product_enabled'),
        ('catalog', '0009_alter_catalog_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='catalog_products', to='product.productvariant'),
        ),
    ]
