# Generated by Django 4.2.1 on 2023-05-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='site_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
