# Generated by Django 4.2.1 on 2023-06-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_setting_email_setting_site_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='email',
            new_name='site_email',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='social_facebook',
            new_name='site_facebook',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='social_instagram',
            new_name='site_instagram',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='social_tiktok',
            new_name='site_tiktok',
        ),
    ]
