# Generated by Django 4.2.1 on 2023-06-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_rename_email_setting_site_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='site_description',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.TextField(max_length=200)),
                ('meta_keywords', models.TextField()),
                ('meta_author', models.CharField(max_length=100)),
                ('meta_robots', models.CharField(max_length=100)),
                ('meta_image', models.ImageField(upload_to='images/site/')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setting.setting')),
            ],
        ),
    ]
