# Generated by Django 4.2.1 on 2023-06-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_alter_setting_site_description_sitemeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemeta',
            options={'verbose_name_plural': 'Site Meta'},
        ),
    ]
