# Generated by Django 4.2.1 on 2023-06-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_alter_sitemeta_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='site_keywords',
        ),
    ]
