# Generated by Django 4.2.1 on 2023-06-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setting.setting')),
            ],
            options={
                'verbose_name_plural': 'Shipping',
            },
        ),
    ]
