# Generated by Django 4.2.1 on 2023-06-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_alter_tax_tax_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingcharge',
            old_name='shipping_charge',
            new_name='amount',
        ),
    ]
