# Generated by Django 4.2.1 on 2023-06-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_setting_site_banner_large_setting_site_banner_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemeta',
            name='test',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
