# Generated by Django 4.2.1 on 2023-06-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_sitemeta_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemeta',
            name='test',
        ),
    ]
