# Generated by Django 4.2.1 on 2023-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0016_remove_sitemeta_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='banner_collection',
            field=models.ImageField(default=1, upload_to='images/site/'),
            preserve_default=False,
        ),
    ]
