# Generated by Django 4.2.1 on 2023-06-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0018_rename_banner_collection_setting_site_banner_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='site_banner_collection',
            new_name='site_banner_collections',
        ),
    ]
