# Generated by Django 4.2.1 on 2023-06-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0019_rename_site_banner_collection_setting_site_banner_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='Enter currency code. Example: USD, EUR, GBP, etc.', max_length=3)),
                ('currency_symbol', models.CharField(help_text='Enter currency symbol. Example: $, €, £, etc.', max_length=5)),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setting.setting')),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
    ]
