# Generated by Django 4.2.1 on 2023-06-29 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0021_alter_currency_currency_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='tax',
            name='city',
            field=models.CharField(default=1, help_text='Enter city name.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tax',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.setting'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Enter tax percentage e.g. 5.00 for 5% tax.', max_digits=10),
        ),
    ]
