# Generated by Django 4.2.1 on 2023-06-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0022_alter_tax_options_tax_city_alter_tax_setting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Enter tax rate e.g. 5.00 for 5% tax.', max_digits=10),
        ),
    ]
