# Generated by Django 4.2.1 on 2023-06-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0023_remove_tax_tax_percentage_tax_tax_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingCharge',
        ),
    ]
