# Generated by Django 4.2.1 on 2023-06-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_order_shipping_charge'),
        ('setting', '0024_delete_shippingcharge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tax',
            new_name='TaxAndShipment',
        ),
    ]
