# Generated by Django 4.2.1 on 2023-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0026_alter_taxandshipment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='site_reg_no',
            field=models.CharField(default='00 000 00', max_length=100),
            preserve_default=False,
        ),
    ]
