# Generated by Django 4.2.1 on 2023-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0027_setting_site_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='site_website',
            field=models.CharField(default='https://nainahcollection.com', max_length=100),
            preserve_default=False,
        ),
    ]
