# Generated by Django 4.2.1 on 2023-07-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0028_setting_site_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
