# Generated by Django 4.2.1 on 2023-07-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0029_lol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lol',
        ),
    ]
