# Generated by Django 4.2.1 on 2023-07-18 03:57

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0030_delete_lol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.setting')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('name', models.CharField(max_length=100)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.setting')),
            ],
        ),
    ]
