# Generated by Django 4.2.1 on 2023-05-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_direccion_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='direccion',
            new_name='pais',
        ),
    ]
