# Generated by Django 4.2.1 on 2023-05-30 20:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_direccion_order_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pais',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
