# Generated by Django 4.2.1 on 2023-06-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pais',
            new_name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('store_pickup', 'Store Pickup')], default='delivery', max_length=20),
        ),
    ]
