# Generated by Django 4.2.1 on 2023-06-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_product_category_alter_product_description_and_more'),
        ('order', '0007_remove_orderitem_price_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order.OrderItem', to='product.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='US', max_length=100),
        ),
    ]
