# Generated by Django 4.2.1 on 2023-06-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_products_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_sell',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
