# Generated by Django 4.2.1 on 2023-06-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_rename_subtotal_order_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sub_total',
            new_name='subtotal',
        ),
    ]
