# Generated by Django 4.2.1 on 2023-06-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_rename_sub_total_order_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='sub_total',
        ),
    ]
