# Generated by Django 4.2.1 on 2023-06-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_alter_tax_tax_percentage'),
        ('order', '0020_rename_subtotal_order_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.shippingcharge'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.tax'),
        ),
    ]
