# Generated by Django 4.2.1 on 2023-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_orderitem_shipping_charge_orderitem_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
