# Generated by Django 4.2.1 on 2023-06-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_orderitem_shipping_charge_alter_orderitem_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_charge',
        ),
    ]
