# Generated by Django 4.2.1 on 2023-06-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
