# Generated by Django 4.2.1 on 2023-06-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
