# Generated by Django 4.2.1 on 2023-06-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0023_remove_tax_tax_percentage_tax_tax_rate'),
        ('order', '0036_alter_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(help_text='Select Tax', on_delete=django.db.models.deletion.PROTECT, to='setting.tax'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
