# Generated by Django 4.2.1 on 2023-07-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
