# Generated by Django 4.2.1 on 2023-07-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_alter_order_address_line_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='United States of America', max_length=100),
        ),
    ]
