# Generated by Django 4.2.1 on 2023-07-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0028_setting_site_website'),
        ('coupon', '0004_alter_coupon_discount_alter_coupon_min_amount'),
        ('order', '0046_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coupon.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(help_text='Select City.', on_delete=django.db.models.deletion.CASCADE, to='setting.taxandshipment'),
        ),
    ]
