# Generated by Django 4.2.1 on 2023-07-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0028_setting_site_website'),
        ('order', '0047_order_coupon_order_discount_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(default=30, help_text='Select City.', on_delete=django.db.models.deletion.CASCADE, to='setting.taxandshipment'),
        ),
    ]
