# Generated by Django 4.2.1 on 2023-07-04 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0028_setting_site_website'),
        ('order', '0049_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(help_text='Select City.', on_delete=django.db.models.deletion.PROTECT, to='setting.taxandshipment'),
        ),
    ]
