# Generated by Django 4.2.1 on 2023-07-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
