# Generated by Django 4.2.1 on 2023-07-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
