name: Django Deploy

on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: sudo docker-compose up -d --build

      - name: Restart Django Service

        run: sudo docker-compose up -d nainah-backend
